version: "3.4"
services:
  docker-shezzy-backend:
    build:
      context: .
      dockerfile: Shezzy.Api/Dockerfile
    container_name: docker-shezzy-backend     
    image: docker-shezzy-backend     
    networks:
      - shezzy_backend 
    ports:
      - "4025:4025"      

networks:
  shezzy_backend:
    name: shezzy_backend
    driver: bridge   
