version: "3.4"
services:
  docker-shezzy-backend:
    build:
      context: .
      dockerfile: Shezzy.Api/Dockerfile
    container_name: docker-shezzy-backend     
    image: docker-shezzy-backend     
    networks:
      - shezzy_backend 
    ports:     
      - "4025:4025"
      - "4026:4026"      
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=B3nSh3z*
      - ASPNETCORE_Kestrel__Certificates__Default__Path=./https/aspnetapp.pfx
networks:
  shezzy_backend:
    name: shezzy_backend
    driver: bridge   
